### PR TITLE
Update .travis.yml to Perl 5.22

### PR DESCRIPTION
**Pull request by viviparous**

### CODE REVIEW

**Comment by theory** [comment]
Thanks!

**Comment by viviparous** [comment]
Let me know if you have other suggestions for this module. I'm participating in Neil Bowers' Perl Pull Request Challenge. 
http://blogs.perl.org/users/neilb/2014/12/take-the-2015-cpan-pull-request-challenge.html

**Comment by theory** [comment]
Well if you're interested in adding features, as opposed to fixing bugs, there are a couple of ideas in [Issues](/theory/dist-zilla-localetextdomain/issues).

**Comment by viviparous** [comment]
I don't object to fixing bugs. I could add a low-complexity new feature but I don't think it would be optimal for me to add a major feature. 


     On Friday, October 16, 2015 12:07 AM, David E. Wheeler <notifications@github.com> wrote:
   

 Well if you're interested in adding features, as opposed to fixing bugs, there are a couple of ideas in Issues.—

**Comment by theory** [comment]
Neither of the suggested items (#2 and #12) are at all complicated. This module is relatively complete in its implementation. These are just nice-to-have items that will simplify things for some people. So have at either one as you wish.

**Pull request merged**
